#!/usr/bin/env python3
"""Build the Exercise 43.14 files (u09 Section 0.7 R8, round 2; D-125):

  Ch43_start_no_mc.xlsx  the pre-Monte-Carlo starting file: model/build/Ch43_outputs.xlsx with Inputs F311,
                         F312, rows 313 to 1312 (draw table and pasted per-run results) and F1321 removed,
                         and Time F16, Operations rows 31, 37 and 39, Checks F8, F13, F14 and F23 and Outputs
                         F44 restored to their pre-Chapter 43 formulas.  It does not contain the answer.
  ch43_draw_table.xlsx   the 1,000 x 29 draw table of R5 (values only, no results columns), seed and
                         parameters stated; the draws sit at the companion's addresses (rows 313 to 1312,
                         columns J to AL) so the block pastes straight onto Inputs.
"""
import os, sys, json
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill

HERE = os.path.dirname(os.path.abspath(__file__))
MODEL = os.path.abspath(os.path.join(HERE, '..', '..'))
BUILD = os.path.join(MODEL, 'build')
sys.path.insert(0, BUILD); sys.path.insert(0, MODEL)
import build_stages as bs     # noqa: E402

START = os.path.join(HERE, 'Ch43_start_no_mc.xlsx')
DRAWS = os.path.join(HERE, 'ch43_draw_table.xlsx')
BLUE = Font(color='0000FF'); YEL = PatternFill('solid', fgColor='FFF2CC'); BOLD = Font(bold=True)


def start_file():
    wb = load_workbook(os.path.join(BUILD, 'Ch43_outputs.xlsx'))
    pre = load_workbook(os.path.join(BUILD, 'Ch42_waterfall.xlsx'))
    ws = wb['Inputs']
    for (r, c) in [k for k in ws._cells if 311 <= k[0] <= 1312 or k[0] == 1321]:
        del ws._cells[(r, c)]
    for sh, r, kind in bs.V13_ROWS + [('Checks', 23, 'F')]:
        w, p = wb[sh], pre[sh]
        w.cell(r, 4).value = p.cell(r, 4).value
        cols = [6] if kind == 'F' else range(10, 10 + 57)
        for c in cols:
            w.cell(r, c).value = p.cell(r, c).value
    o = wb['Outputs']['F44']
    wrap = '=IF(Inputs!$F$312=1,0,'
    assert o.value.startswith(wrap) and o.value.endswith(')')
    o.value = '=' + o.value[len(wrap):-1]
    cv = wb['Cover']
    cv['D29'].value = None
    note = ['Exercise 43.14 starting file Ch43_start_no_mc.xlsx: Ch43_outputs.xlsx without the Monte Carlo block (pre-run state; model version 1.4).',
            'Removed: Inputs F311 and F312, rows 313 to 1312 (draw table and per-run results) and F1321; Time F16, Operations rows 31, 37 and 39,',
            'Checks F8, F13, F14 and F23 and Outputs F44 hold their pre-Chapter 43 formulas. Paste the draws from ch43_draw_table.xlsx and build the rest (u09 Section 0.5, Ch 43 row).',
            'Reconciles in every scenario (1 to 15); master check 0. Solution: model/build/Ch43_outputs.xlsx (do not open it first).',
            'Verification: model/exercises/README.md.']
    for j, t in enumerate(note):
        c = cv.cell(bs.STAGE_NOTE_ROW + j, 4, t); c.font = Font(bold=(j == 0))
    wb.calculation.fullCalcOnLoad = True
    wb.save(START)


def draw_table():
    import build_excel_p as bx, case_p as cp
    DR = cp.mc_draws()
    wb = Workbook(); ws = wb.active; ws.title = 'Draws'
    ws['A1'] = 'Case P Monte Carlo draw table (Exercise 43.14; u09 Section 0.7 R5; P-F42 inputs; D-125). Values only: no results.'; ws['A1'].font = Font(bold=True, size=12)
    lines = ['Generated by model/case_p.py v1.4 (mc_draws), seed 20180717, 1,000 runs; the draws sit at the companion addresses: copy J313:AL1312 and paste onto Inputs J313:AL1312.',
             'Columns J to AI: availability shock for operating years 1 to 26 (points; normal, mean 0, standard deviation 2.0, truncated to -10 and +5; independent).',
             'Column AJ: dispatch factor when available (%; one draw per run; triangular 55.0, mode 76.5, 85.0).',
             'Column AK: non-recoverable heat-rate degradation (% a year; one draw per run; normal 0.12, standard deviation 0.04, floored at 0); replaces Inputs F127 in the run.',
             'Column AL: FX drift factor per year applied to the FC FX path (KCR depreciation drift normal 5.19% a year, standard deviation 3.0%), replaces Time F16 in the run.',
             'Number of shocked operating years: 26 (Inputs F1321 in the companion).']
    for j, t in enumerate(lines):
        ws.cell(2 + j, 1, t)
    ws.cell(312, 4, 'Run').font = BOLD
    heads = [f'OY{k} shock' for k in range(1, 27)] + ['Dispatch', 'HR degradation', 'FX drift']
    for j, h in enumerate(heads):
        ws.cell(312, 10 + j, h).font = BOLD
    for r in range(DR.shape[0]):
        ws.cell(313 + r, 4, f'Run {r + 1}')
        for j in range(DR.shape[1]):
            c = ws.cell(313 + r, 10 + j, float(DR[r, j])); c.font = BLUE; c.fill = YEL
    ws.freeze_panes = 'J313'
    wb.save(DRAWS)
    return DR.shape


if __name__ == '__main__':
    old = os.path.join(HERE, 'Ex43_14_start.xlsx')
    if os.path.exists(old):
        os.remove(old)
    start_file(); print('written', START)
    print('written', DRAWS, draw_table())
