#!/usr/bin/env python3
"""
Case P reference model: Belanou Combined Cycle Power Project (Republic of Kessara).

Python mirror and computational source of truth for the Case P companion workbook
(Case_P_Model.xlsx, generated by build_excel_p.py).  Pure Python + numpy.

Reads  : model/inputs_case_p.json
Writes : model/outputs_case_p.json   (every period series and scalar, keyed by name)
         model/case_p_report.md       (human-readable summary tables)

Structure (mirrors the workbook sheets)
  Time         monthly construction timeline (Aug 2018 - Dec 2022, 53 months) and
               semiannual operating timeline (2018H2 - 2046H2, 57 periods)
  Construction monthly uses of funds (budget, actual overrun items, VAT)
  Funding      monthly sources: pro rata 75:25 debt/equity (FC-type scenarios) with a
               closed-form ("affine") gross-up of IDC/fees/premium/DSRA, or the actual
               funding cascade (committed facilities, LDs, DSU, standby + contingent equity)
  Operations   semiannual revenue (capacity, VOM, fuel pass-through), opex, working capital
  Tax          holiday, deferred depreciation, thin cap, minimum turnover tax
  Debt         tranches (ECA, A-loan, B-loan, commercial, standby, 2025 bond), swap
  Waterfall    CFADS, debt service, DSRA, lock-up, sweeps, distributions, dividend trap
  Financials   income statement, balance sheet, cash flow
  Ratios       DSCR (period and 12-month historic), LLCR, PLCR
  Returns      equity and project IRR (XIRR on dated flows)

Circularities and how they are resolved
  1. Construction: IDC, commitment fees, upfront fees, ECA premium and DSRA all depend on the
     facility size, which is 75% of the total funding requirement (T).  Python iterates
     T_{n+1} = U + F(0.75 T_n) to a tolerance of USD 1,000 (0.001 USD m).  The workbook solves
     the same fixed point in closed form: every month's balance is carried as
     alpha_m + beta_m * T, so T = alpha_end / (g - beta_end).  Both are reported.
  2. Sculpting: sculpted debt service depends on CFADS, CFADS depends on tax, and tax depends
     on interest (and on the shareholder-loan path).  Python iterates the whole model:
     profile -> model -> CFADS -> re-sculpted profile, to a tolerance of USD 1,000 on every
     installment.  After financial close the repayment profile is a contractual schedule
     (percentages of the loan), so the workbook carries the converged profile on the Inputs
     sheet and shows the live sculpting calculation with a check row (live minus contract).
     The same applies to the COD re-sculpting (2021) and the 2025 bond profile.
"""
import json, math, os, sys, copy
from datetime import date, timedelta
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
INP = json.load(open(os.path.join(HERE, 'inputs_case_p.json')))
TOL = 0.001          # USD m (USD 1,000) convergence tolerance

# ----------------------------------------------------------------------------------------
# Date helpers
# ----------------------------------------------------------------------------------------
def add_months(d, n):
    y, m = d.year + (d.month - 1 + n) // 12, (d.month - 1 + n) % 12 + 1
    return date(y, m, 1)

def eomonth(d):
    return add_months(date(d.year, d.month, 1), 1) - timedelta(days=1)

def serial(d):            # Excel serial date
    return (d - date(1899, 12, 30)).days

def months_between(a, b):  # whole months from a (1st of month) to b (1st of month)
    return (b.year - a.year) * 12 + b.month - a.month

NM, NS = 53, 57
M_START = [add_months(date(2018, 8, 1), m) for m in range(NM)]
M_END = [eomonth(d) for d in M_START]
M_DAYS = [(M_END[m] - M_START[m]).days + 1 for m in range(NM)]
M_PER = [((d.year - 2018) * 12 + d.month - 7) // 6 for d in M_START]     # 0-based period index
S_START = [add_months(date(2018, 7, 1), 6 * t) for t in range(NS)]
S_END = [eomonth(add_months(S_START[t], 5)) for t in range(NS)]
S_DAYS = [(S_END[t] - S_START[t]).days + 1 for t in range(NS)]
S_YEAR = [d.year for d in S_START]
S_HALF = [1 if d.month == 1 else 2 for d in S_START]
S_LABEL = [f"{S_YEAR[t]}H{S_HALF[t]}" for t in range(NS)]
def tix(label):
    return S_LABEL.index(label)

# ----------------------------------------------------------------------------------------
# Inputs (scalars)
# ----------------------------------------------------------------------------------------
cap = INP['capex_usd_m']; ppa = INP['ppa']; opx = INP['opex']; dbt = INP['debt']
G = 0.75                                   # gearing cap (debt share of total funding)
TR = ['ECA', 'A', 'B', 'COM']              # base tranches, pro rata
SHARE = np.array([0.30, 0.22, 0.10, 0.38])
MARGIN = np.array([1.35, 3.65, 3.40, 4.10])           # % (commercial steps up, see com_margin)
CFEE = np.array([0.45, 0.75, 0.85, 0.40 * 4.10])      # % pa commitment fee (construction)
UPF = np.array([1.10, 1.25, 1.50, 2.15])              # % of commitment at FC
GU = np.array([1.0, 1.0, 1.0, 1 / 0.9])               # WHT gross-up factor (commercial 10%)
ECA_PREM = 0.1085
PRI = 0.0115 * 0.90                                   # PRI premium on commercial balance, pa
SWAP_FIX = 2.947
CAS = 0.42826
SB_COMMIT, SB_CFEE = 46.0, 0.60
CE_COMMIT = 15.4
LNTP = 14.20
SHL_RATE = 9.5
EQ_SC, EQ_SHL = 0.20, 0.80
K_GAS = 1000 * 1.108 / 1055056       # MMBtu (HHV) per MWh per kJ/kWh(LHV)

def com_margin(year):
    return 4.10 if year <= 2025 else (4.60 if year <= 2029 else 5.10)

SB_MARGIN_BLEND = None   # standby: 60% commercial (margin+0.25, grossed up), 40% ABDB (3.65+0.25)

# ----------------------------------------------------------------------------------------
# Macro paths
# ----------------------------------------------------------------------------------------
mac = INP['macro']
def cpi_tables():
    us_a = {int(k): v for k, v in mac['us_cpi_annual_avg_change_pct'].items() if k.isdigit()}
    kc_a = {int(k): v for k, v in mac['kessara_cpi_annual_avg_change_pct'].items() if k.isdigit()}
    for y in range(2027, 2050):
        us_a.setdefault(y, mac['us_cpi_annual_avg_change_pct']['2027_onward'])
    for y in range(2028, 2050):
        kc_a.setdefault(y, mac['kessara_cpi_annual_avg_change_pct']['2028_onward'])
    us_fc = {y: (us_a[y] if y <= 2017 else 2.2) for y in range(2015, 2050)}
    kc_fc = {y: (kc_a[y] if y <= 2017 else 7.5) for y in range(2015, 2050)}
    us_rf = {y: (us_a[y] if y <= 2021 else 2.2) for y in range(2015, 2050)}
    kc_rf = {y: (kc_a[y] if y <= 2021 else 7.5) for y in range(2015, 2050)}
    return {'ACT': (us_a, kc_a), 'FC': (us_fc, kc_fc), 'CODRF': (us_rf, kc_rf)}
CPI = cpi_tables()

FC_FWD = [2.52, 2.79, 2.94, 3.02, 3.06, 3.09, 3.09, 3.11, 3.11] + [3.12] * (NS - 9)
_lib = [2.52, 2.87, 2.20, 1.91, 0.37, 0.25, 0.16, 0.34, 2.94]
_sofr = [4.86, 5.47, 5.16, 5.22, 4.25, 4.17, 3.62, 3.58, 3.45, 3.45]
ACT_BASE = _lib + [s + CAS for s in _sofr] + [3.50 + CAS] * (NS - 19)
RF_BASE = _lib[:7] + FC_FWD[7:]
FX_ACT_GIVEN = [524.6, 539.1, 551.3, 566.0, 579.8, 597.4, 609.6, 654.9, 830.3, 1052.8, 1043.8,
                1093.1, 1050.7, 1035.6, 1023.8, 1028.9, 1043.9]
POLICY_ACT = {2018: 13.5, 2019: 13.5, 2020: 13.5, 2021: 13.5, 2022: 19.0, 2023: 27.0,
              2024: 24.5, 2025: 18.0}
FX_FC0, FX_D = 519.4, 1.075 / 1.022

# ----------------------------------------------------------------------------------------
# Scenarios
# ----------------------------------------------------------------------------------------
BASE = dict(macro='FC', constr='FC', cod_delay=0, capex=1.0, avail_d=0.0, dispatch=76.5,
            hr_f=1.0, fo_f=1.0, gas_f=1.0, rate_shift=0.0, deval=0.0, lag_days=0,
            delay_days=0, crisis=0, ins_step=0, profile='FC', ld_prep=0, waiver=0, refi=0,
            cap_charge_f=1.0, shl_share=EQ_SHL, miniperm=1)
SCENARIOS = {
    1: dict(name='FC base'),
    2: dict(name='FC banking', dispatch=72.0),
    3: dict(name='FC downside', avail_d=-6.5, hr_f=1.015, fo_f=1.10),
    4: dict(name='Sens: availability -3 points', avail_d=-3.0),
    5: dict(name='Sens: heat rate +2%', hr_f=1.02),
    6: dict(name='Sens: fixed opex +10%', fo_f=1.10),
    7: dict(name='Sens: capex +10% funded pro rata', capex=1.10),
    8: dict(name='Sens: COD delay 6 months, no LDs', cod_delay=6),
    9: dict(name='Sens: base rate +200 bps (unhedged)', rate_shift=2.0),
    10: dict(name='Sens: KCR devaluation 40%, 90-day lag', deval=0.40, lag_days=90),
    11: dict(name='Sens: SEKA pays 120 days late for 12 months', delay_days=120),
    12: dict(name='Sens: dispatch 50%', dispatch=50.0),
    13: dict(name='Sens: gas price +30%', gas_f=1.30),
    14: dict(name='COD re-forecast (2021 lenders case)', macro='CODRF', constr='ACT',
             profile='COD', ld_prep=1),
    15: dict(name='Actual history', macro='ACT', constr='ACT', profile='COD', ld_prep=1,
             crisis=1, ins_step=1, waiver=1, refi=1),
}
def scen(i, **over):
    p = dict(BASE); p.update(SCENARIOS[i]); p.update(over); p['id'] = i
    return p
SHOCK_T0 = tix('2022H1')      # start of devaluation / payment-delay sensitivities (2 periods)

# ----------------------------------------------------------------------------------------
# Contract (post-close fixed terms) -- produced by the sizing runs, then held fixed
# ----------------------------------------------------------------------------------------
CONTRACT = {}
ERRS = set()      # seeded audit errors E1-E10 (Chapter 44 exercise); empty in the reference model

# ----------------------------------------------------------------------------------------
# Macro builder
# ----------------------------------------------------------------------------------------
def build_macro(p):
    us, kc = CPI[p['macro']]
    base_s = {'FC': FC_FWD, 'ACT': ACT_BASE, 'CODRF': RF_BASE}[p['macro']]
    base_s = np.array(base_s) + p['rate_shift'] * (np.arange(NS) >= SHOCK_T0)
    # FX semiannual average
    fx = np.zeros(NS)
    for t in range(NS):
        if p['macro'] == 'FC':
            fx[t] = FX_FC0 * p.get('fx_d', FX_D) ** ((t + 0.5) / 2)
        elif p['macro'] == 'ACT':
            fx[t] = FX_ACT_GIVEN[t] if t < 17 else fx[t - 1] * ((1 + kc[S_YEAR[t]] / 100) / (1 + us[S_YEAR[t]] / 100)) ** 0.5
        else:
            fx[t] = FX_ACT_GIVEN[t] if t <= 6 else fx[t - 1] * FX_D ** 0.5
    if p['deval'] > 0:
        fx = fx * np.where(np.arange(NS) >= SHOCK_T0, 1 / (1 - p['deval']), 1.0)
    fx_m = np.array([FX_FC0 * p.get('fx_d', FX_D) ** ((m + 0.5) / 12) if p['macro'] == 'FC' else fx[M_PER[m]]
                     for m in range(NM)])
    base_m = np.array([base_s[M_PER[m]] for m in range(NM)])
    if p['rate_shift']: base_m = np.array([({'FC': FC_FWD, 'ACT': ACT_BASE, 'CODRF': RF_BASE}[p['macro']])[M_PER[m]] for m in range(NM)])
    pol = np.array([13.5 if p['macro'] == 'FC' else POLICY_ACT.get(M_START[m].year, 15.5)
                    for m in range(NM)])

    # price indices: monthly geometric spread, 100 at Nov 2016
    def idx(g, y, mo):  # index at end of month 'mo' of year y
        v = 100 * (1 + g[2016] / 100) ** (1 / 12)
        for yy in range(2017, y):
            v *= 1 + g[yy] / 100
        return v * (1 + g[y] / 100) ** (mo / 12)
    out = {}
    for nm, g in (('us', us), ('kc', kc)):
        cost = np.zeros(NS)   # index at Mar (H1) / Sep (H2) of the period year
        tar = np.zeros(NS)    # index 3 months before reset: Sep prior year (H1) / Mar (H2)
        for t in range(NS):
            y = S_YEAR[t]
            if t == 0:
                cost[t] = idx(g, 2018, 9)
                tar[t] = idx(g, 2018, 3)
            else:
                f = ((1 + g[y - 1] / 100) ** 0.25 * (1 + g[y] / 100) ** 0.25) if S_HALF[t] == 1 \
                    else (1 + g[y] / 100) ** 0.5
                cost[t] = cost[t - 1] * f
                tar[t] = cost[t - 1]
            if 'E3' in ERRS:
                tar[t] = cost[t] * (1 + g[y] / 100) ** 0.25
        base18 = idx(g, 2018, 6)
        out[nm + '_cost'] = cost; out[nm + '_tar'] = tar; out[nm + '_base18'] = base18
        out[nm + '_cf'] = cost / base18
    out.update(base_s=base_s, base_m=base_m, fx=fx, fx_m=fx_m, pol=pol)
    return out

# ----------------------------------------------------------------------------------------
# Construction uses (monthly)
# ----------------------------------------------------------------------------------------
PROF = cap['profiles']
EPC_FC = list(PROF['epc_payment_pct_by_month_base'].values())
EPC_ACT = list(PROF['epc_payment_pct_by_month_actual'].values())
OWN_FC = list(PROF['owners_costs_pct_by_month_base'].values())
OVR = INP['events']['construction_overrun']
# timing of actual overrun items (modeler timing assumptions; amounts from the Case Bible)
OVERRUN_TIMING = [   # (name, amount, first month index (0 = Aug 2018), number of months)
    ('COVID variation order', OVR['covid_variation_order_usd_m'], 26, 6),       # Oct20-Mar21
    ('Grid-event prolongation settlement', OVR['grid_event_prolongation_settlement_usd_m'], 39, 1),
    ('Project company COVID measures', OVR['covid_owner_measures_usd_m'], 20, 12),  # Apr20-Mar21
    ('Additional resettlement compensation', OVR['additional_resettlement_compensation_usd_m'], 29, 6),
    ('Customs duty settlement', OVR['customs_duty_settlement_usd_m'], 37, 1),
    ('Insurance extension premium', OVR['insurance_extension_premium_usd_m'], 33, 1),
    ('Additional start-up fuel, net', OVR['additional_start_up_fuel_net_usd_m'], 38, 2),
    ('EAR deductible', OVR['ear_deductible_borne_usd_m'], 35, 1),
    ('Additional lenders advisor costs', OVR['additional_lenders_advisor_costs_usd_m'], 33, 7),
]
EXT_OWNERS = OVR['extended_owners_costs_usd_m']     # months 34-40 (index 33-39)
RECEIPT_M = 39                                       # Nov 2021: taking-over

def cod_date(p):
    if p['constr'] == 'ACT':
        return date(2021, 12, 1)
    return add_months(date(2021, 5, 1), p['cod_delay'])

def construction_uses(p, mac_):
    """Base uses before financing costs, per month (USD m), and VAT (KCR m)."""
    cod = cod_date(p); nc = months_between(date(2018, 8, 1), cod)
    u = {k: np.zeros(NM) for k in ['epc', 'owners', 'insurance', 'dev', 'advisors',
                                    'contingency', 'wc', 'overrun', 'onshore_kcr']}
    cx = p['capex']
    if p['constr'] == 'FC':
        pct = np.zeros(NM); pct[:33] = EPC_FC
        if p['cod_delay']:
            pct[32] -= 7.5; pct[32 + p['cod_delay']] += 7.5
        prog = pct.copy(); prog[0] = 0; prog[nc - 1] -= 7.5
        u['epc'] = 571.84 * cx * pct / 100
        own = np.zeros(NM); own[:33] = OWN_FC
        own[33:nc] = 2.75
        u['owners'] = 46.18 * cx * own / 100
        u['contingency'] = 38.40 * cx * prog / prog.sum()
    else:
        pct = np.zeros(NM); pct[:40] = EPC_ACT
        off = 571.84 * pct / 100 * 489.17 / 571.84
        onk = pct / 100 * 82.67 * 519.4
        u['epc'] = off + onk / mac_['fx_m']
        own = np.zeros(NM); own[:33] = OWN_FC
        u['owners'] = 46.18 * own / 100
        u['owners'][33:40] += EXT_OWNERS / 7
        for _, amt, m0, n in OVERRUN_TIMING:
            u['overrun'][m0:m0 + n] += amt / n
    u['onshore_kcr'] = pct / 100 * 82.67 * 519.4 * cx
    u['insurance'][0] = 0.85 * 7.62 * cx; u['insurance'][17] += 0.15 * 7.62 * cx
    u['dev'][0] = 21.43 + 11.20
    u['advisors'][0] = 0.70 * 8.97 * cx
    u['advisors'][1:nc] += 0.30 * 8.97 * cx / (nc - 1)
    u['wc'][nc - 1] = 5.35 * cx
    u['base_total'] = sum(u[k] for k in ['epc', 'owners', 'insurance', 'dev', 'advisors',
                                          'contingency', 'wc', 'overrun'])
    # VAT on onshore EPC (KCR), refunded after 9 months; UBK facility at policy + 2.50%
    vat = 0.18 * u['onshore_kcr']
    refund = np.zeros(NM); refund[9:] = vat[:-9]
    bal = np.zeros(NM); vint = np.zeros(NM)
    for m in range(NM):
        op = bal[m - 1] if m else 0.0
        vint[m] = op * (mac_['pol'][m] + 2.5) / 100 * M_DAYS[m] / 365 / mac_['fx_m'][m]
        bal[m] = op + vat[m] - refund[m]
    u.update(vat_kcr=vat, vat_refund_kcr=refund, vat_bal_kcr=bal, vat_int=vint,
             vat_usd=vat / mac_['fx_m'], nc=nc, cod=cod)
    return u

# ----------------------------------------------------------------------------------------
# Funding (monthly)
# ----------------------------------------------------------------------------------------
def first_ds_period(p):
    cod = cod_date(p)
    t_cod = [t for t in range(NS) if S_START[t] <= cod <= S_END[t]][0]
    return t_cod, t_cod + 1

def fund_end_month(p):
    t_cod, _ = first_ds_period(p)
    return max(m for m in range(NM) if M_PER[m] == t_cod)

def ds_rate_vector(p, mac_, t):
    """Per-tranche all-in loan rate for period t (fraction of balance per period)."""
    base = mac_['base_s'][t]; dcf = S_DAYS[t] / 360
    mg = MARGIN.copy(); mg[3] = com_margin(S_YEAR[t])
    r = (base + mg) / 100 * (0.5 if 'E4' in ERRS else dcf) * GU
    r[3] += PRI * S_DAYS[t] / 365
    return r

def dsra_coeffs(p, mac_, prof, N_s):
    """DSRA at COD = d1 . balances + d0 (next-period debt service on fully drawn balances)."""
    _, t1 = first_ds_period(p)
    r = ds_rate_vector(p, mac_, t1)
    d1 = prof[t1] / prof[t1:].sum() + r
    d0 = N_s[t1] * (SWAP_FIX / 100 * 0.5 - mac_['base_s'][t1] / 100 * S_DAYS[t1] / 360) * (-1 if 'E10' in ERRS else 1)
    return d1, d0

def month_rates(mac_, m):
    base = mac_['base_m'][m]; dcf = M_DAYS[m] / 360
    rho = (base + MARGIN) / 100 * ((1 / 12) if 'E4' in ERRS else dcf) * GU          # construction: commercial margin 4.10
    rho[3] += PRI * M_DAYS[m] / 365
    kap = CFEE / 100 * dcf
    return rho, kap

def funding_fc(p, mac_, u, prof, N_m, N_s, D_fixed=None, mode='size'):
    """FC-type funding, pro rata debt/equity.
    mode 'size'    : Python sizing loop; D = G*T (or D_fixed), g = D/T, T by fixed-point iteration
    mode 'contract': committed amounts D_c, E_c from the FC sizing; g = D_c/(D_c+E_c); one pass
    mode 'regross' : g = D_c/(D_c+E_c) and D = g*T (capex +10%, COD delay); T by iteration
    The workbook's closed-form (affine) gross-up is reproduced for cross-check."""
    fe = fund_end_month(p); nc = u['nc']
    d1, d0 = dsra_coeffs(p, mac_, prof, N_s)
    if mode == 'contract':
        Dc = CONTRACT['D']; gc = Dc / (Dc + CONTRACT['E'])
        if 'E7' in ERRS:
            ds_ = (d1 * SHARE * Dc).sum() + d0
            gc = (Dc - ds_) / (Dc + CONTRACT['E'] - ds_)
        r = _fund_fc_pass(p, mac_, u, Dc, gc, fe, nc, d1, d0, N_m)
        r['iterations'] = 1; r['T'] = r['uses'].sum()
        g_aff = G
    else:
        gfix = None if mode == 'size' else CONTRACT['D'] / (CONTRACT['D'] + CONTRACT['E'])
        T = u['base_total'].sum() * 1.15; it = 0
        while True:
            it += 1
            if mode == 'size' and 'E7' in ERRS:
                if it == 1: D, g = G * T, G
                elif D_fixed is None: D, g = Dn_, G
                else: g = g * D_fixed / Dn_; D = D_fixed
            elif mode == 'size':
                D = G * T if D_fixed is None else D_fixed; g = D / T
            else:
                g = gfix; D = g * T
            r = _fund_fc_pass(p, mac_, u, D, g, fe, nc, d1, d0, N_m)
            Tn = r['uses'].sum(); Dn_ = r['debt_draw'].sum()
            if abs(Tn - T) < 1e-9 and ('E7' not in ERRS or abs(Dn_ - D) < 1e-9):
                T = Tn; break
            T = Tn
            if it > 500: raise RuntimeError('funding did not converge')
        r['iterations'] = it; r['T'] = T
        g_aff = G if mode == 'size' else gfix
    # closed-form (affine) gross-up as built in the workbook: balance_m = alpha_m + beta_m * T
    a = b = 0.0; A = np.zeros(NM); B = np.zeros(NM); g = g_aff
    den = 1 - ECA_PREM * SHARE[0] * g
    for m in range(NM):
        if m > fe: A[m], B[m] = a, b; continue
        rho, kap = month_rates(mac_, m)
        rr = (SHARE * rho).sum(); kk = (SHARE * kap).sum()
        const = (u['base_total'][m] + u['vat_int'][m] + 0.255 / 12
                 + N_m[m] * (SWAP_FIX / 100 / 12 - mac_['base_m'][m] / 100 * M_DAYS[m] / 360)
                 + SB_COMMIT * SB_CFEE / 100 * M_DAYS[m] / 360)
        cod_m = (m == nc)
        const += d0 if cod_m else 0.0
        a_new = a + g / den * (const + rr * a - kk * a)
        b_new = b + g / den * (rr * b + kk * (g - b) + (g * (SHARE * UPF / 100).sum() if m == 0 else 0)
                               + (g * (SHARE * d1).sum() if cod_m else 0))
        a, b = a_new, b_new; A[m], B[m] = a, b
    r['alpha'] = A; r['beta'] = B; r['g_aff'] = g; r['T_closed_form'] = A[fe] / (g - B[fe])
    return r

def _fund_fc_pass(p, mac_, u, D, g, fe, nc, d1, d0, N_m):
    Dk = SHARE * D
    bal = np.zeros(4); out = {k: np.zeros(NM) for k in
        ['idc', 'swap', 'pri', 'cfee', 'upfront', 'agency', 'eca_prem', 'dsra', 'uses',
         'debt_draw', 'equity', 'equity_cash', 'shl_contrib', 'sc_contrib', 'shl_capint',
         'shl_bal', 'fin_costs', 'sb_cfee', 'loan_int']}
    for k in range(4):
        out['draw_' + TR[k]] = np.zeros(NM); out['bal_' + TR[k]] = np.zeros(NM)
        out['idc_' + TR[k]] = np.zeros(NM)
    shl = 0.0
    den = 1 - ECA_PREM * SHARE[0] * g
    for m in range(NM):
        if m > fe:
            for k in range(4): out['bal_' + TR[k]][m] = bal[k]
            out['shl_bal'][m] = shl; continue
        rho, kap = month_rates(mac_, m)
        idc_k = bal * (mac_['base_m'][m] + MARGIN) / 100 * ((1 / 12) if 'E4' in ERRS else M_DAYS[m] / 360) * GU
        pri = PRI * bal[3] * M_DAYS[m] / 365
        swap = N_m[m] * (SWAP_FIX / 100 / 12 - mac_['base_m'][m] / 100 * M_DAYS[m] / 360) * (-1 if 'E10' in ERRS else 1)
        cfee = ((Dk - bal) * kap).sum()
        sbf = SB_COMMIT * SB_CFEE / 100 * M_DAYS[m] / 360
        upf = (Dk * UPF / 100).sum() if m == 0 else 0.0
        dsra = (d1 * Dk).sum() + d0 if m == nc else 0.0
        X = (u['base_total'][m] + u['vat_int'][m] + idc_k.sum() + pri + swap + cfee + sbf
             + upf + 0.255 / 12 + dsra)
        if 'E7' in ERRS:   # seeded error: DSRA funded 100% by senior debt
            draw = (g * (X - dsra) + dsra) / den
            uses = X + ECA_PREM * SHARE[0] * draw
        else:
            uses = X / den
            draw = g * uses
        prem = ECA_PREM * SHARE[0] * draw
        for k in range(4):
            out['draw_' + TR[k]][m] = SHARE[k] * draw
            out['idc_' + TR[k]][m] = idc_k[k]
        bal = bal + SHARE * draw
        eq = uses - draw
        shl_int = shl * SHL_RATE / 100 * M_DAYS[m] / 365 if m < nc else 0.0
        shl += shl_int + p['shl_share'] * eq
        out['idc'][m] = idc_k.sum() + pri + swap; out['loan_int'][m] = idc_k.sum()
        out['swap'][m] = swap; out['pri'][m] = pri; out['cfee'][m] = cfee; out['sb_cfee'][m] = sbf
        out['upfront'][m] = upf; out['agency'][m] = 0.255 / 12; out['eca_prem'][m] = prem
        out['dsra'][m] = dsra; out['uses'][m] = uses; out['debt_draw'][m] = draw
        out['equity'][m] = eq; out['equity_cash'][m] = eq - (LNTP if m == 0 else 0)
        out['shl_contrib'][m] = p['shl_share'] * eq; out['sc_contrib'][m] = (1 - p['shl_share']) * eq
        out['shl_capint'][m] = shl_int; out['shl_bal'][m] = shl
        out['fin_costs'][m] = (idc_k.sum() + pri + swap + cfee + sbf + upf + 0.255 / 12 + prem
                               + u['vat_int'][m])
        for k in range(4): out['bal_' + TR[k]][m] = bal[k]
    out['D'] = D; out['Dk'] = Dk; out['g'] = g
    out['sb_draw'] = np.zeros(NM); out['ce_draw'] = np.zeros(NM); out['bal_SB'] = np.zeros(NM)
    out['ld_used'] = np.zeros(NM); out['ld_pool'] = np.zeros(NM); out['base_fund'] = out['uses'].copy()
    out['ld_leftover'] = 0.0
    return out

def funding_act(p, mac_, u, prof, N_m, N_s):
    """Actual funding cascade: committed FC facilities pro rata, then LDs/DSU, then standby
    and contingent equity 75:25."""
    fe = fund_end_month(p); nc = u['nc']
    Dk = np.array(CONTRACT['Dk']); E_fc = CONTRACT['E']; g = Dk.sum() / (Dk.sum() + E_fc)
    d1, d0 = dsra_coeffs(p, mac_, prof, N_s)
    _, t1 = first_ds_period(p)
    rsb_t1 = sb_rate(mac_, t1)
    bal = np.zeros(4); sb = 0.0; shl = 0.0; pool = 0.0; eq_cum = 0.0
    out = {k: np.zeros(NM) for k in
        ['idc', 'swap', 'pri', 'cfee', 'upfront', 'agency', 'eca_prem', 'dsra', 'uses',
         'debt_draw', 'equity', 'equity_cash', 'shl_contrib', 'sc_contrib', 'shl_capint',
         'shl_bal', 'fin_costs', 'sb_cfee', 'sb_draw', 'ce_draw', 'bal_SB', 'ld_used',
         'ld_pool', 'base_fund', 'ld_received', 'loan_int', 'sb_int']}
    for k in range(4):
        out['draw_' + TR[k]] = np.zeros(NM); out['bal_' + TR[k]] = np.zeros(NM)
        out['idc_' + TR[k]] = np.zeros(NM)
    for m in range(NM):
        if m > fe:
            for k in range(4): out['bal_' + TR[k]][m] = bal[k]
            out['bal_SB'][m] = sb; out['shl_bal'][m] = shl; out['ld_pool'][m] = pool; continue
        base = mac_['base_m'][m]; dcf = M_DAYS[m] / 360
        idc_k = bal * (base + MARGIN) / 100 * dcf * GU
        sbi = sb * sb_rate_m(base) * dcf
        pri = PRI * bal[3] * M_DAYS[m] / 365
        swap = N_m[m] * (SWAP_FIX / 100 / 12 - base / 100 * dcf)
        cfee = ((Dk - bal) * CFEE / 100 * dcf).sum()
        sbf = (SB_COMMIT - sb) * SB_CFEE / 100 * dcf
        upf = (Dk * UPF / 100).sum() if m == 0 else 0.0
        dsra = ((d1 * bal).sum() + sb * (prof[t1] / prof[t1:].sum() + rsb_t1) + d0) if m == nc else 0.0
        X = (u['base_total'][m] + u['vat_int'][m] + idc_k.sum() + sbi + pri + swap + cfee + sbf
             + upf + 0.255 / 12 + dsra)
        HD = Dk.sum() - bal.sum()
        bdebt = min(g * X / (1 - ECA_PREM * SHARE[0] * g), HD)
        prem = ECA_PREM * SHARE[0] * bdebt
        uses = X + prem
        bfund = bdebt / g
        R1 = uses - bfund
        rec = (OVR['epc_delay_lds_usd_m'] + OVR['dsu_proceeds_usd_m']) if m == RECEIPT_M else 0.0
        avail = pool + rec
        ldu = min(R1, avail); pool = avail - ldu
        R2 = R1 - ldu
        sbd, ce = 0.75 * R2, 0.25 * R2
        for k in range(4):
            out['draw_' + TR[k]][m] = SHARE[k] * bdebt; out['idc_' + TR[k]][m] = idc_k[k]
        bal = bal + SHARE * bdebt; sb += sbd
        eq = bfund - bdebt + ce
        shl_int = shl * SHL_RATE / 100 * M_DAYS[m] / 365 if m < nc else 0.0
        shl += shl_int + p['shl_share'] * eq
        out['idc'][m] = idc_k.sum() + sbi + pri + swap; out['loan_int'][m] = idc_k.sum()
        out['sb_int'][m] = sbi
        out['swap'][m] = swap; out['pri'][m] = pri; out['cfee'][m] = cfee; out['sb_cfee'][m] = sbf
        out['upfront'][m] = upf; out['agency'][m] = 0.255 / 12; out['eca_prem'][m] = prem
        out['dsra'][m] = dsra; out['uses'][m] = uses; out['debt_draw'][m] = bdebt + sbd
        out['equity'][m] = eq; out['equity_cash'][m] = eq - (LNTP if m == 0 else 0)
        out['shl_contrib'][m] = p['shl_share'] * eq; out['sc_contrib'][m] = (1 - p['shl_share']) * eq
        out['shl_capint'][m] = shl_int; out['shl_bal'][m] = shl
        out['sb_draw'][m] = sbd; out['ce_draw'][m] = ce; out['bal_SB'][m] = sb
        out['ld_used'][m] = ldu; out['ld_pool'][m] = pool; out['base_fund'][m] = bfund
        out['ld_received'][m] = rec
        out['fin_costs'][m] = (idc_k.sum() + sbi + pri + swap + cfee + sbf + upf + 0.255 / 12
                               + prem + u['vat_int'][m])
        for k in range(4): out['bal_' + TR[k]][m] = bal[k]
    out['D'] = Dk.sum(); out['Dk'] = Dk; out['g'] = g; out['T'] = out['uses'].sum()
    out['ld_leftover'] = pool; out['iterations'] = 1
    return out

def sb_rate_m(base):
    """Standby all-in rate (% pa, before day count): 60% commercial (margin 4.10+0.25, grossed
    up for 10% WHT), 40% ABDB (3.65+0.25)."""
    return (0.6 * (base + 4.10 + 0.25) / 0.9 + 0.4 * (base + 3.65 + 0.25)) / 100

def sb_rate(mac_, t):
    base = mac_['base_s'][t]; cm = com_margin(S_YEAR[t])
    return (0.6 * (base + cm + 0.25) / 0.9 + 0.4 * (base + 3.65 + 0.25)) / 100 * S_DAYS[t] / 360

# ----------------------------------------------------------------------------------------
# Main run
# ----------------------------------------------------------------------------------------
def run(p, prof=None, N_m=None, N_s=None, bond_prof=None, D_fixed=None, gearing=None):
    """Run one scenario. prof: contractual repayment profile (array NS, fractions summing to 1).
    N_m/N_s: swap notional (monthly / semiannual opening). bond_prof: bond % of face."""
    global G
    G_saved = G
    if gearing is not None: G = gearing
    ERRS.clear(); ERRS.update(p.get('errs', ()))
    try:
        return _run(p, prof, N_m, N_s, bond_prof, D_fixed)
    finally:
        G = G_saved

def _run(p, prof, N_m, N_s, bond_prof, D_fixed):
    R = {}
    mac_ = build_macro(p)
    u = construction_uses(p, mac_)
    if prof is None:
        prof = np.array(CONTRACT['prof_FC'] if p['profile'] == 'FC' else CONTRACT['prof_COD'])
    if N_m is None: N_m = np.array(CONTRACT['N_m'])
    if N_s is None: N_s = np.array(CONTRACT['N_s'])
    if bond_prof is None and p['refi']: bond_prof = np.array(CONTRACT['prof_BOND'])
    if p['constr'] == 'FC':
        mode = p.get('fund_mode') or ('regross' if (p['capex'] != 1.0 or p['cod_delay']) else 'contract')
        f = funding_fc(p, mac_, u, prof, N_m, N_s, D_fixed, mode)
    else:
        f = funding_act(p, mac_, u, prof, N_m, N_s)
    R['mac'] = mac_; R['u'] = u; R['f'] = f; R['prof'] = prof; R['N_m'] = N_m; R['N_s'] = N_s
    cod = u['cod']; expiry = add_months(cod, 300) - timedelta(days=1)
    t_cod, t1 = first_ds_period(p)
    fe = fund_end_month(p)
    S = {}   # semiannual rows
    def z(): return np.zeros(NS)
    # ---- timing
    om = z(); opdays = z(); oms = z(); ome = z()
    for t in range(NS):
        s_ = max(S_START[t], cod); e_ = min(S_END[t], expiry)
        if e_ >= s_:
            om[t] = months_between(s_, add_months(date(e_.year, e_.month, 1), 1))
            opdays[t] = (e_ - s_).days + 1
        oms[t] = min(max(months_between(cod, S_START[t]), 0), 300)
        ome[t] = oms[t] + om[t]
    last_op = max(t for t in range(NS) if om[t] > 0)
    S.update(om=om, opdays=opdays, oms=oms, ome=ome)
    flag_ds = np.array([1.0 if t >= t1 else 0.0 for t in range(NS)])
    # ---- plant
    av_prof = INP['plant']['availability_profile_pct_by_operating_year_cycle']['values']
    shock = p.get('avail_shock')       # Monte Carlo: availability shock by operating year (points)
    def av_oy(oy): return av_prof[(oy - 1) % 8] + (shock[oy - 1] if shock is not None and oy <= len(shock) else 0.0)
    A = z(); Ap = z(); yrs = z()
    for t in range(NS):
        if om[t] == 0: continue
        oya = int(oms[t] // 12) + 1
        ma = min(ome[t], oya * 12) - oms[t]; mb = om[t] - ma
        Ap[t] = (ma * av_oy(oya) + mb * av_oy(oya + 1)) / om[t]
        yrs[t] = (oms[t] + ome[t]) / 24
    A = np.where(om > 0, Ap + p['avail_d'], 0.0)
    act = p['constr'] == 'ACT'
    C = p.get('C_override') or (581.9 if act else 588.4)
    HRg = p.get('HR_override') or (6286 if act else 6261)
    OF = (1 - 0.0015 * yrs) * 0.99
    HRF = (1 + p.get('hr_nr', 0.12) / 100 * yrs) * 1.008
    E = C * 730 * om * A / 100 * p['dispatch'] / 100 * OF          # MWh
    HRa = HRg * HRF * 1.023 * p['hr_f']
    HRc = 6323 * (1 + 0.001 * yrs) * 1.023
    yrf = np.array(S_YEAR) - 2018
    pgas = 5.86 * 1.02 ** yrf * p['gas_f']
    gas = E * HRa * K_GAS                                           # MMBtu
    fuel_rev = E * HRc * K_GAS * pgas / 1e6 * ((76.5 / p['dispatch']) if 'E9' in ERRS else 1.0)
    fuel_cost = gas * pgas / 1e6
    top_vol = 0.8 * 72400 * opdays
    top_short = np.maximum(0, top_vol - gas)
    top_pay = top_short * pgas / 1e6
    esc = 1.015 ** yrf
    gta_res = 96500 * opdays * 0.62 * esc / 1e6
    gta_com = gas * 0.19 * esc / 1e6
    S.update(avail=A, avail_prof=Ap, yrs=yrs, out_factor=OF, energy=E, hr_act=HRa, hr_con=HRc,
             gas_price=pgas, gas_mmbtu=gas, fuel_rev=fuel_rev, fuel_cost=fuel_cost,
             top_vol=top_vol, top_short=top_short, top_pay=top_pay, gta_res=gta_res, gta_com=gta_com)
    # ---- tariff
    m_ = mac_; fx = m_['fx']
    usT, kcT = m_['us_tar'] / 100, m_['kc_tar'] / 100
    cap_chg = 14.36 * p['cap_charge_f'] * (0.8 + 0.2 * usT)
    fom_chg = 2.31 * (0.62 * usT + 0.38 * kcT * 462.35 / fx)
    cpr = cap_chg + fom_chg
    avf = (A / 90.0) if 'E1' in ERRS else np.minimum(1, A / 90.0)
    CP = C * 1000 * om * cpr * avf / 1e6
    vom_rate = 3.86 * (0.7 * usT + 0.3 * kcT * 462.35 / fx)
    VOM = E * vom_rate / 1e6
    nonfuel = CP + VOM
    rev = nonfuel + fuel_rev + gta_res + gta_com + top_pay
    S.update(cap_charge=cap_chg, fom_charge=fom_chg, cpr=cpr, avail_factor=avf, cap_pay=CP,
             vom_rate=vom_rate, vom=VOM, nonfuel_rev=nonfuel, revenue=rev,
             us_tar=m_['us_tar'], kc_tar=m_['kc_tar'], us_cf=m_['us_cf'], kc_cf=m_['kc_cf'],
             fx=fx, base=m_['base_s'])
    # ---- opex
    us_cf, kc_cf = m_['us_cf'], m_['kc_cf']
    fo = p['fo_f']; mf = om / 12
    om_fix = 7.92 * (0.65 * us_cf + 0.35 * kc_cf * 516.8 / fx) * mf * fo
    om_inc = 0.60 * np.clip((A - 92) / 3, -1, 1) * us_cf * mf * (om > 0)
    ltsa_fix = 2.64 * us_cf * mf * fo
    eoh = (1 if 'E2' in ERRS else 2) * (8059 * np.divide(A, Ap, out=np.zeros(NS), where=Ap > 0) + 38 * 10) * mf
    ltsa_var = eoh * 486 * us_cf / 1e6
    step = np.array([1.18 if (p['ins_step'] and t >= tix('2022H2')) else 1.0 for t in range(NS)])
    insur = 4.37 * us_cf * mf * step * fo
    ga = 3.18 * (0.5 * us_cf + 0.5 * kc_cf * 516.8 / fx) * mf * fo
    land = 368.0 * kc_cf / fx * mf * fo
    comm = 0.0055 * nonfuel
    consum = 1.08 * (0.7 * us_cf + 0.3 * kc_cf * 516.8 / fx) * E / 1e6
    agency = 0.255 * mf
    prg = 0.0075 * 41.5 * mf
    vat_int_ops = np.array([sum(u['vat_int'][m] for m in range(NM) if M_PER[m] == t and m > fe)
                            for t in range(NS)])
    fxl = z()
    if p['crisis']:
        for k_, v in INP['events']['offtaker_crisis']['fx_conversion_losses_usd_m'].items():
            fxl[tix(k_)] = v
    # major maintenance outside LTSA: spend in period containing month 7 of OY k
    mm_2018 = z()
    for t in range(NS):
        if om[t] == 0: continue
        k = int((ome[t] - 7) // 12) + 1
        if k >= 1 and oms[t] < (k - 1) * 12 + 7 <= ome[t] and k <= 24:
            mm_2018[t] = 9.47 if k % 8 == 0 else (2.18 if k % 4 == 0 else 0.0)
    mm = mm_2018 * us_cf
    # handback reserve from OY20 (months 229..300)
    hb_m = np.maximum(0, np.minimum(ome, 300) - np.maximum(oms, 228))
    hb_contr = 1.85 * us_cf * hb_m / 12
    opex_fixed = om_fix + om_inc + ltsa_fix + ltsa_var + insur + ga + land + comm + consum + agency + prg
    pass_cost = fuel_cost + gta_res + gta_com + top_pay
    hb_works = np.where(np.arange(NS) == last_op, hb_contr.sum(), 0.0)
    opex = opex_fixed + pass_cost + vat_int_ops + fxl + mm + hb_works
    S.update(om_fixed=om_fix, om_incentive=om_inc, ltsa_fixed=ltsa_fix, eoh=eoh, ltsa_var=ltsa_var,
             insurance=insur, ga=ga, land=land, community_levy=comm, consumables=consum,
             agency=agency, prg_fee=prg, vat_int_ops=vat_int_ops, fx_loss=fxl, mm_spend=mm,
             mm_2018=mm_2018, opex_om=opex_fixed, pass_cost=pass_cost, opex=opex,
             hb_months=hb_m, hb_contr_req=hb_contr, hb_works=hb_works)
    # ---- crisis: overdue receivables, gas arrears, late payment interest
    over = z(); lpi_acc = z(); lpi_rec = z()
    crisis = INP['events']['offtaker_crisis']
    if p['crisis']:
        for k_, v in crisis['overdue_receivables_usd_m_period_end'].items():
            tt = [t for t in range(NS) if S_END[t] == date.fromisoformat(k_)][0]
            over[tt] = v
        settle = date(2024, 3, 21)
        for t in range(NS):
            prev = over[t - 1] if t else 0.0
            dd = max(0, min((S_END[t] - S_START[t]).days + 1, (settle - S_START[t]).days))
            lpi_acc[t] = (prev + over[t]) / 2 * (m_['base_s'][t] - (CAS if t >= 9 else 0) + 2.0) / 100 * dd / 360
        tot = lpi_acc.sum() * 0.6
        for lab, sh in (('2024H1', 3 / 15), ('2024H2', 6 / 15), ('2025H1', 6 / 15)):
            lpi_rec[tix(lab)] = tot * sh
    gas_arr = GAS_ARREARS_SHARE * over
    S.update(overdue=over, lpi_accrued=lpi_acc, lpi_received=lpi_rec, gas_arrears=gas_arr)
    ebitda = rev - opex + lpi_rec
    S['ebitda'] = ebitda
    # ---- working capital
    rdays = np.full(NS, 45.0)
    xdays = np.zeros(NS)     # extra days on SEKA's capacity and VOM payments (sensitivities)
    if p['delay_days'] or p['lag_days']:
        xdays[SHOCK_T0:SHOCK_T0 + 2] = p['delay_days'] + p['lag_days']
    od = np.where(opdays > 0, opdays, 1)
    fin = np.arange(NS) >= last_op
    ar = np.where(fin, 0, rev / od * rdays + nonfuel / od * xdays)
    pay_gas = np.where(fin, 0, (fuel_cost + top_pay) / od * 45)
    pay_gta = np.where(fin, 0, (gta_res + gta_com) / od * 30)
    pay_om = np.where(fin, 0, (om_fix + om_inc + ltsa_fix + ltsa_var) / od * 30)
    pay_oth = np.where(fin, 0, (insur + ga + land + comm + consum + agency + prg) / od * 30)
    nwc = ar + over - pay_gas - pay_gta - pay_om - pay_oth - gas_arr
    dnwc = nwc - np.concatenate([[0], nwc[:-1]])
    inv_rel = np.where(np.arange(NS) == last_op, 5.35 * p['capex'], 0.0)
    S.update(rec_days=rdays, extra_days=xdays, ar=ar, pay_gas=pay_gas, pay_gta=pay_gta, pay_om=pay_om, pay_oth=pay_oth,
             nwc=nwc, dnwc=dnwc, inv_release=inv_rel)
    # ---- MMRA
    mm_contr = np.array([mm[t + 1:t + 7].sum() / 6 for t in range(NS)])
    mm_bal = np.cumsum(mm_contr - mm)
    S.update(mm_contr=mm_contr, mmra_bal=mm_bal)
    # ---- capitalized cost (book and tax)
    ld_rec = f['ld_received'].sum() if 'ld_received' in f else 0.0
    perf_ld = OVR['performance_lds_usd_m']['total'] if p['ld_prep'] else 0.0
    capcost = (f['uses'][:fe + 1].sum() - f['dsra'].sum() - u['wc'].sum() + f['shl_capint'].sum()
               - ld_rec - perf_ld)
    R['ld_rec'] = ld_rec; R['perf_ld'] = perf_ld
    R['capcost'] = capcost
    # ---------------- semiannual loop: debt, tax, waterfall, accounts ----------------------
    # balances at end of funding period
    nT = 6   # ECA, A, B, COM, SB, BOND
    names = TR + ['SB', 'BOND']
    bal0 = np.array([f['bal_' + k][fe] for k in TR] + [f['bal_SB'][fe], 0.0])
    B = np.zeros((nT, NS)); Bo = np.zeros((nT, NS)); P = np.zeros((nT, NS)); I = np.zeros((nT, NS))
    LDp = np.zeros((nT, NS)); RF = np.zeros((nT, NS)); SW = np.zeros((nT, NS)); DFo = np.zeros((nT, NS))
    DFc = np.zeros((nT, NS)); DFn = np.zeros((nT, NS)); DFr = np.zeros((nT, NS)); SCH = np.zeros((nT, NS))
    rows = {k: z() for k in [
        'swap', 'pri', 'pcg', 'waiver_fee', 'refi_costs', 'unwind', 'bond_face', 'interest_total',
        'principal_total', 'ds', 'senior_costs', 'tax', 'cit', 'mtt', 'taxable', 'ti_pre', 'pool_open',
        'pool_add', 'pool_use', 'pool_close', 'loss_use', 'loss_close', 'dep_full', 'dep_hol', 'dep_cur',
        'shl_int', 'shl_ded', 'thin_frac', 'int_ded', 'cfads', 'avail_cash', 'dsra_open', 'dsra_draw',
        'dsra_target', 'dsra_topup', 'dsra_release', 'dsra_close', 'shortfall', 'cash_after_ds',
        'hb_contr', 'hb_bal', 'hb_release', 'cash_dist', 'dist_ok', 'lockup', 'lu_count', 'lu_sweep',
        'mp_sweep', 'lu_close', 'shl_int_paid', 'shl_prin', 'div', 'trap_close', 'shl_open', 'shl_close',
        'ni', 're', 'book_dep', 'int_exp', 'dt', 'dt_exp', 'tax_exp', 'dscr', 'dscr_hist', 'eod',
        'released', 'comp_acct', 'rate_k_dummy', 'equity_dist', 'final_dist', 'lpi', 'int_cap',
        'ds_sched_next', 'book_nbv', 'tax_nbv', 'hold_rate', 'mtt_frac', 'nonhol_frac', 'cash_open',
        'ld_cash', 'sweep_lu_flag', 'sc_bal', 'cwip'
    ]}
    rr = rows
    # schedule helpers
    def rem(t): return prof[t:].sum()
    shl = f['shl_bal'][fe]; sc_bal = f['sc_contrib'].sum()
    pool = 0.0; loss = 0.0; dsra = 0.0; mmra = 0.0; hb = 0.0; lu = 0.0
    trap = 0.0; re_ = 0.0; comp = 0.0; prev_lock = 0; released = 0.0; dt_prev = 0.0
    taxcost = capcost
    # depreciation per month (full)
    dep_m_plant = 0.92 * taxcost / 240; dep_m_bld = 0.05 * taxcost / 300; dep_m_int = 0.03 * taxcost / 60
    bond_F = 0.0; deferred23 = np.zeros(nT); t23 = tix('2023H2')
    def mrg(t):
        v = np.array([1.35, 3.65, 3.40, com_margin(S_YEAR[t]), 0.0, 0.0])
        if p['waiver'] and tix('2023H2') <= t <= tix('2024H2'):
            v[:5] += 0.50
        return v
    def tranche_rate(t):   # fraction per period, for bank tranches 0..4 (SB blended), bond 5
        base = m_['base_s'][t]; dcf = S_DAYS[t] / 360; mg = mrg(t)
        r = np.zeros(nT)
        r[:4] = (base + mg[:4]) / 100 * (0.5 if 'E4' in ERRS else dcf) * GU
        up = 0.5 if (p['waiver'] and tix('2023H2') <= t <= tix('2024H2')) else 0.0
        r[4] = (0.6 * (base + com_margin(S_YEAR[t]) + 0.25 + up) / 0.9 + 0.4 * (base + 3.65 + 0.25 + up)) / 100 * dcf
        r[5] = 7.875 / 100 * 0.5
        return r
    swap_share = np.array([1.0 if not (p['refi'] and t > tix('2025H1')) else 0.52 for t in range(NS)])
    tR = tix('2025H1') if p['refi'] else -1
    for t in range(NS):
        # opening balances
        if t <= t_cod:
            Bo[:, t] = 0
        else:
            Bo[:, t] = B[:, t - 1]
        if t == t_cod:
            B[:, t] = bal0
        DFo[:, t] = DFc[:, t - 1] if t else 0
        r = tranche_rate(t)
        if t > t_cod:
            I[:, t] = Bo[:, t] * r
            # scheduled principal (pro rata to remaining contractual profile)
            if rem(t) > 1e-12:
                SCH[:5, t] = (Bo[:5, t] - DFo[:5, t]) * prof[t] / rem(t)
            if p['waiver'] and t == t23:
                DFn[:5, t] = 0.6 * SCH[:5, t]; deferred23 = DFn[:, t].copy()
            if p['waiver'] and tix('2024H1') <= t <= tix('2025H2'):
                DFr[:, t] = np.minimum(deferred23 / 4, DFo[:, t])
            P[:5, t] = SCH[:5, t] - DFn[:5, t] + DFr[:5, t]
            if Bo[5, t] > 0:
                P[5, t] = min(bond_F * bond_prof[t], Bo[5, t])
                SCH[5, t] = P[5, t]
            DFc[:, t] = DFo[:, t] + DFn[:, t] - DFr[:, t]
            rr['swap'][t] = N_s[t] * swap_share[t] * (SWAP_FIX / 100 * 0.5 - m_['base_s'][t] / 100 * S_DAYS[t] / 360) * (-1 if 'E10' in ERRS else 1)
            rr['pri'][t] = PRI * Bo[3, t] * S_DAYS[t] / 365
            rr['pcg'][t] = 0.011 * 0.5 * Bo[5, t] * (95.0 / bond_F if bond_F else 0)
            if p['waiver'] and t == t23:
                rr['waiver_fee'][t] = 0.0025 * Bo[:5, t].sum()
            # LD prepayment June 2022
            if p['ld_prep'] and t == tix('2022H1'):
                after = Bo[:5, t] - P[:5, t]
                LDp[:5, t] = OVR['performance_lds_usd_m']['total'] * after / after.sum()
            # refinancing June 2025
            if t == tR:
                RF[[2, 3, 4], t] = Bo[[2, 3, 4], t] - P[[2, 3, 4], t] - LDp[[2, 3, 4], t]
                DFc[[2, 3, 4], t] = 0
                prepaid = RF[:, t].sum()
                # swap unwind: 48% of notional, flat 3.68%
                mtm = 0.0
                for s in range(t + 1, NS):
                    mtm += 0.48 * N_s[s] * (3.68 - SWAP_FIX) / 100 * 0.5 / (1 + 0.0368 / 2) ** (s - t)
                rr['unwind'][t] = mtm
                bond_F = (prepaid + 3.10 + 0.0075 * 95.0 - mtm) / (0.99512 - 0.01)
                rr['bond_face'][t] = bond_F
                rr['refi_costs'][t] = bond_F * (1 - 0.99512) + 0.01 * bond_F + 3.10 + 0.0075 * 95.0
        rr['int_cap'][t] = 0.0
        rr['interest_total'][t] = I[:, t].sum()
        rr['principal_total'][t] = P[:, t].sum()
        rr['senior_costs'][t] = I[:, t].sum() + rr['swap'][t] + rr['pri'][t] + rr['pcg'][t]
        rr['ds'][t] = rr['senior_costs'][t] + P[:, t].sum()
        # ---------------- tax
        HE = 96 if 'E5' in ERRS else 60
        hol = max(0, min(ome[t], HE) - min(oms[t], HE))
        red = max(0, min(ome[t], 96) - min(max(oms[t], HE), 96))
        full = om[t] - hol - red
        dep_full = (dep_m_plant * max(0, min(ome[t], 240) - min(oms[t], 240))
                    + dep_m_bld * max(0, min(ome[t], 300) - min(oms[t], 300))
                    + dep_m_int * max(0, min(ome[t], 60) - min(oms[t], 60)))
        dep_hol = (dep_m_plant + dep_m_bld) * hol + dep_m_int * max(0, min(ome[t], min(60, HE)) - min(oms[t], min(60, HE)))
        dep_cur = dep_full - dep_hol
        rr['shl_open'][t] = shl if t >= t_cod else 0.0
        shl_int = shl * SHL_RATE / 100 * opdays[t] / 365 if t >= t_cod else 0.0
        if t == t_cod:  # interest accrues from COD
            shl_int = shl * SHL_RATE / 100 * opdays[t] / 365
        thin = min(1.0, 3 * (sc_bal + max(0.0, re_)) / shl) if (shl > 0 and t >= t_cod) else 1.0
        shl_ded = shl_int * thin
        int_ded = rr['senior_costs'][t] + rr['waiver_fee'][t] + rr['refi_costs'][t] - rr['unwind'][t]
        nh = (om[t] - hol) / om[t] if om[t] > 0 else 0.0
        ti_pre = (ebitda[t] - int_ded - shl_ded) * nh - dep_cur
        luse = min(loss, max(0.0, ti_pre)); ti2 = ti_pre - luse
        puse = min(pool, max(0.0, ti2)); ti3 = ti2 - puse
        lnew = max(0.0, -ti_pre)
        taxable = max(0.0, ti3)
        hr = (red * 15 + full * 30) / (red + full) / 100 if (red + full) > 0 else 0.0
        cit = taxable * hr
        mtt = 0.005 * nonfuel[t] * ((red + full) / om[t] if om[t] > 0 else 0.0)
        tax = max(cit, mtt)
        rr['pool_open'][t] = pool
        pool = pool + (0.0 if 'E6' in ERRS else dep_hol) - puse; loss = loss - luse + lnew
        rr.update()
        for k_, v in (('dep_full', dep_full), ('dep_hol', dep_hol), ('dep_cur', dep_cur), ('shl_int', shl_int),
                      ('thin_frac', thin), ('shl_ded', shl_ded), ('int_ded', int_ded), ('ti_pre', ti_pre),
                      ('loss_use', luse), ('pool_use', puse), ('pool_add', dep_hol), ('pool_close', pool),
                      ('loss_close', loss), ('taxable', taxable), ('hold_rate', hr), ('cit', cit), ('mtt', mtt),
                      ('tax', tax), ('nonhol_frac', nh), ('mtt_frac', (red + full) / om[t] if om[t] > 0 else 0)):
            rr[k_][t] = v
        # ---------------- CFADS
        cfads = ebitda[t] - tax - dnwc[t] - mm_contr[t] + mm[t] + inv_rel[t]
        rr['cfads'][t] = cfads
        # ---------------- waterfall
        if p['ld_prep'] and t == t_cod:
            comp = OVR['performance_lds_usd_m']['total']
        ld_cash = 0.0
        if p['ld_prep'] and t == tix('2022H1'):
            ld_cash = comp; comp = 0.0
        rr['comp_acct'][t] = comp; rr['ld_cash'][t] = ld_cash
        if t == t_cod:
            dsra = f['dsra'].sum(); lu = f['ld_leftover']
        cash_open = lu + trap
        rr['cash_open'][t] = cash_open
        avail = cfads + cash_open
        rr['avail_cash'][t] = avail
        need = rr['senior_costs'][t] + rr['waiver_fee'][t] + P[:, t].sum()
        short = max(0.0, need - avail)
        dr = min(dsra, short)
        rr['dsra_open'][t] = dsra; rr['dsra_draw'][t] = dr; rr['shortfall'][t] = short - dr
        cad = max(0.0, avail - need)
        # DSRA target: next-period scheduled debt service on balances after this period's
        # scheduled payments and non-cash-dependent prepayments (LDs, refinancing)
        Bn = Bo[:, t] - P[:, t] - LDp[:, t] - RF[:, t] if t > t_cod else B[:, t].copy()
        if t == tR: Bn[5] = bond_F
        tgt = 0.0
        if t + 1 < NS and t >= t_cod:
            r1 = tranche_rate(t + 1)
            DFn_next = DFc[:, t]
            for k in range(5):
                if Bn[k] > 1e-9:
                    sched = (Bn[k] - DFn_next[k]) * prof[t + 1] / rem(t + 1) if rem(t + 1) > 1e-12 else 0.0
                    drep = min(deferred23[k] / 4, DFn_next[k]) if (p['waiver'] and tix('2024H1') <= t + 1 <= tix('2025H2')) else 0.0
                    tgt += sched + drep + Bn[k] * r1[k]
            if Bn[5] > 1e-9:
                tgt += min(bond_F * bond_prof[t + 1], Bn[5]) + Bn[5] * r1[5] + 0.011 * 0.5 * Bn[5] * 95.0 / bond_F
            tgt += N_s[t + 1] * swap_share[t + 1] * (SWAP_FIX / 100 * 0.5 - m_['base_s'][t + 1] / 100 * S_DAYS[t + 1] / 360) * (-1 if 'E10' in ERRS else 1)
            tgt += PRI * Bn[3] * S_DAYS[t + 1] / 365
        rr['dsra_target'][t] = tgt
        dsra_after = dsra - dr
        top = min(cad, max(0.0, tgt - dsra_after))
        rel = max(0.0, dsra_after - tgt)
        dsra = dsra_after + top - rel
        rr['dsra_topup'][t] = top; rr['dsra_release'][t] = rel; rr['dsra_close'][t] = dsra
        cash = cad - top + rel
        rr['cash_after_ds'][t] = cad
        # handback reserve
        hbc = min(cash, hb_contr[t]); hb += hbc
        hbr = hb if t == last_op else 0.0
        hb -= hbr
        cash = cash - hbc + hbr
        rr['hb_contr'][t] = hbc; rr['hb_bal'][t] = hb; rr['hb_release'][t] = hbr
        # distribution test (historic DSCR, 12 months)
        dsr = cfads / rr['ds'][t] if rr['ds'][t] > 1e-9 else 0.0
        rr['dscr'][t] = dsr
        if t >= 1 and rr['ds'][t - 1] > 1e-9:
            dh = (cfads + rr['cfads'][t - 1]) / (rr['ds'][t] + rr['ds'][t - 1])
        else:
            dh = dsr
        rr['dscr_hist'][t] = dh if rr['ds'][t] > 1e-9 else 0.0
        first_rep = rr['principal_total'][:t + 1].sum() > 1e-9
        eod = 1.0 if (rr['ds'][t] > 1e-9 and dh < 1.10) else 0.0
        waived = p['waiver'] and t in (tix('2023H1'), t23)
        rr['eod'][t] = eod
        in_waiver = p['waiver'] and t >= tix('2023H1')
        if in_waiver and t > t23:
            cond = (dh >= 1.25) and (rr['dscr_hist'][t - 1] >= 1.25 if t - 1 > t23 else False) \
                   and (dsra >= tgt - 1e-6)
            released = max(released, 1.0 if cond else 0.0)
        rr['released'][t] = released
        ok = first_rep and dh >= 1.20 and dsra >= tgt - 1e-6 and (eod == 0 or waived) \
            and rr['ds'][t] > 1e-9
        if in_waiver and not released:
            ok = False
        ok = ok or t == last_op and rr['ds'][t] <= 1e-9 or (rr['ds'][t] <= 1e-9 and t > t_cod and Bo[:, t].sum() < 1e-9)
        rr['dist_ok'][t] = 1.0 if ok else 0.0
        lock = (not ok) and first_rep and rr['ds'][t] > 1e-9
        cnt = (prev_lock + 1) if lock else 0
        prev_lock = cnt
        rr['lockup'][t] = 1.0 if lock else 0.0; rr['lu_count'][t] = cnt
        lusw = 0.0; mpsw = 0.0
        sweep_ok = cnt >= 2 and not in_waiver
        if not ok:
            if sweep_ok:
                lusw = min(cash, Bo[:5, t].sum() - P[:5, t].sum() - LDp[:5, t].sum() - RF[:5, t].sum())
                after = Bo[:5, t] - P[:5, t] - LDp[:5, t] - RF[:5, t]
                if after.sum() > 1e-9:
                    SW[:5, t] = lusw * after / after.sum()
            lu = cash - lusw; trap = 0.0
            dist = 0.0
        else:
            lu = 0.0
            if S_YEAR[t] >= 2027 and p['miniperm']:
                comm_after = Bo[3, t] - P[3, t] - LDp[3, t] - RF[3, t]
                mpsw = min(0.5 * cash, comm_after)
                SW[3, t] += mpsw
            dist = cash - mpsw
        rr['lu_sweep'][t] = lusw; rr['mp_sweep'][t] = mpsw; rr['lu_close'][t] = lu
        rr['cash_dist'][t] = dist
        # SHL and dividends
        due = shl_int
        sip = min(dist, due) if ok else 0.0
        shl = shl + shl_int - sip
        spr = min(dist - sip, shl) if ok else 0.0
        shl -= spr
        # accounting NI
        book_dep = capcost / 300 * om[t]
        int_exp = rr['senior_costs'][t] + rr['waiver_fee'][t] + rr['refi_costs'][t] - rr['unwind'][t] + shl_int
        tax_nbv = taxcost - sum(rr['dep_full'][:t + 1])
        book_nbv = capcost - sum(capcost / 300 * om[:t + 1])
        dtv = 0.30 * (book_nbv - (tax_nbv + pool)) if t >= t_cod else 0.0
        dt_exp = dtv - dt_prev; dt_prev = dtv
        ni = ebitda[t] - book_dep - int_exp - tax - dt_exp
        dcap = max(0.0, re_ + ni)
        dv = min(dist - sip - spr, dcap) if ok else 0.0
        trap = (dist - sip - spr - dv) if ok else 0.0
        if t == last_op:   # liquidation at PPA expiry: everything left goes to shareholders
            extra = trap + lu + dsra + mmra
            dv += extra; trap = 0.0; lu = 0.0
            dsra = 0.0
            rr['dsra_close'][t] = 0.0
            rr['final_dist'][t] = extra
        re_ = re_ + ni - dv
        rr['shl_int_paid'][t] = sip; rr['shl_prin'][t] = spr; rr['div'][t] = dv; rr['trap_close'][t] = trap
        rr['shl_close'][t] = shl if t >= t_cod else 0.0; rr['ni'][t] = ni; rr['re'][t] = re_; rr['book_dep'][t] = book_dep
        rr['int_exp'][t] = int_exp; rr['dt'][t] = dtv; rr['dt_exp'][t] = dt_exp
        rr['tax_exp'][t] = tax + dt_exp; rr['book_nbv'][t] = book_nbv; rr['tax_nbv'][t] = tax_nbv
        rr['equity_dist'][t] = sip + spr + dv
        rr['sc_bal'][t] = sc_bal
        # closing balances
        if t > t_cod:
            B[:, t] = Bo[:, t] - P[:, t] - LDp[:, t] - RF[:, t] - SW[:, t]
            if t == tR: B[5, t] = bond_F
    # store
    for k, nm in enumerate(names):
        S['bal_open_' + nm] = Bo[k]; S['bal_close_' + nm] = B[k]; S['principal_' + nm] = P[k]
        S['interest_' + nm] = I[k]; S['ld_prepay_' + nm] = LDp[k]; S['refi_prepay_' + nm] = RF[k]
        S['sweep_' + nm] = SW[k]; S['sched_' + nm] = SCH[k]; S['deferred_' + nm] = DFc[k]
        S['deferred_new_' + nm] = DFn[k]; S['deferred_repay_' + nm] = DFr[k]
    S.update(rr)
    S['flag_ds'] = flag_ds; S['prof'] = prof; S['N_s'] = N_s * swap_share
    S['debt_close'] = B.sum(0); S['debt_open'] = Bo.sum(0)
    R['S'] = S; R['last_op'] = last_op; R['t_cod'] = t_cod; R['t1'] = t1; R['fe'] = fe
    R['bond_F'] = bond_F; R['p'] = p
    ratios(R)
    returns(R)
    financials(R)
    return R


# ----------------------------------------------------------------------------------------
# Financial statements (IFRS basis, USD functional currency; see report)
# ----------------------------------------------------------------------------------------
def financials(R):
    S = R['S']; f = R['f']; u = R['u']; fe = R['fe']; t_cod = R['t_cod']
    z = lambda: np.zeros(NS)
    # construction-phase cumulative amounts at each period end (monthly -> semiannual)
    cum = lambda arr: np.array([arr[[m for m in range(NM) if M_PER[m] <= t]].sum() for t in range(NS)])
    cap_m = f['uses'] - f['dsra'] - u['wc'] + f['shl_capint'] - f.get('ld_received', np.zeros(NM))
    cwip = cum(cap_m) - np.where(np.arange(NS) >= t_cod, R['perf_ld'], 0.0)
    ppe = np.where(np.arange(NS) >= t_cod, S['book_nbv'], cwip)
    S['ppe'] = ppe
    debt = np.where(np.arange(NS) < t_cod, cum(f['debt_draw']), S['debt_close'])
    shl = np.where(np.arange(NS) < t_cod, cum(f['shl_contrib'] + f['shl_capint']), S['shl_close'])
    sc = cum(f['sc_contrib'])
    inv = np.where((np.arange(NS) >= t_cod) & (np.arange(NS) < R['last_op']), 5.35 * R['p']['capex'], 0.0)
    if True:   # inventory funded in the last construction month
        inv = np.where(np.arange(NS) < t_cod, cum(u['wc']), inv)
    ld_pool = np.where(np.arange(NS) < t_cod, cum(f.get('ld_received', np.zeros(NM)) - f.get('ld_used', np.zeros(NM))), 0.0)
    cash = (S['dsra_close'] + S['mmra_bal'] + S['hb_bal'] + S['lu_close'] + S['trap_close']
            + S['comp_acct'] + ld_pool)
    ar = S['ar'] + S['overdue']
    pay = S['pay_gas'] + S['pay_gta'] + S['pay_om'] + S['pay_oth'] + S['gas_arrears']
    dta = np.where(S['dt'] < 0, -S['dt'], 0.0); dtl = np.where(S['dt'] > 0, S['dt'], 0.0)
    re_ = np.where(np.arange(NS) < t_cod, 0.0, S['re'])
    assets = ppe + cash + ar + inv + dta
    liab = debt + shl + pay + dtl
    eq = sc + re_
    S.update(bs_cash=cash, bs_ar=ar, bs_inv=inv, bs_dta=dta, bs_assets=assets, bs_debt=debt,
             bs_shl=shl, bs_pay=pay, bs_dtl=dtl, bs_sc=sc, bs_re=re_, bs_liab_eq=liab + eq,
             bs_check=assets - liab - eq, bs_ld_pool=ld_pool)

GAS_ARREARS_SHARE = 0.80   # modeler calibration: energy-charge share of SEKA arrears matched by deferred SNHK/GCK payables

# ----------------------------------------------------------------------------------------
# Ratios
# ----------------------------------------------------------------------------------------
def ratios(R):
    S = R['S']; NSs = NS
    debt_cost = S['senior_costs']
    rate = np.divide(debt_cost, S['debt_open'], out=np.zeros(NS), where=S['debt_open'] > 1e-9)
    S['allin_rate'] = rate
    # LLCR: PV of CFADS to final maturity at the all-in rate (+ DSRA balance) / debt outstanding
    fm = max([t for t in range(NS) if S['debt_open'][t] > 1e-9], default=0)
    pv = np.zeros(NS + 1); pvp = np.zeros(NS + 1)
    for t in range(NS - 1, -1, -1):
        r_ = rate[t] if rate[t] > 0 else rate[fm]
        pv[t] = (S['cfads'][t] + pv[t + 1]) / (1 + r_) if t <= fm else 0.0
        pvp[t] = (S['cfads'][t] + pvp[t + 1]) / (1 + r_) if t <= R['last_op'] else 0.0
    llcr = np.divide(pv[:NS], S['debt_open'], out=np.zeros(NS), where=S['debt_open'] > 1e-9)
    llcr_d = np.divide(pv[:NS] + S['dsra_open'], S['debt_open'], out=np.zeros(NS), where=S['debt_open'] > 1e-9)
    plcr = np.divide(pvp[:NS], S['debt_open'], out=np.zeros(NS), where=S['debt_open'] > 1e-9)
    S['pv_cfads_loan'] = pv[:NS]; S['llcr'] = llcr; S['llcr_dsra'] = llcr_d; S['plcr'] = plcr
    S['final_maturity_t'] = fm

# ----------------------------------------------------------------------------------------
# Returns
# ----------------------------------------------------------------------------------------
def xirr(flows, dates, guess=0.15):
    d0 = dates[0]
    yrs = np.array([(d - d0).days / 365.0 for d in dates]); cf = np.array(flows)
    r = guess
    for _ in range(200):
        v = (cf / (1 + r) ** yrs).sum(); dv = (-yrs * cf / (1 + r) ** (yrs + 1)).sum()
        nr = r - v / dv
        if abs(nr - r) < 1e-12: r = nr; break
        r = nr
    return r

def xnpv(rate, flows, dates, d0=None):
    d0 = d0 or dates[0]
    return sum(c / (1 + rate) ** ((d - d0).days / 365.0) for c, d in zip(flows, dates))

def returns(R):
    S = R['S']; f = R['f']; u = R['u']; fe = R['fe']
    dates = [date(2018, 2, 5)] + M_START + S_END
    eq = [-LNTP] + list(-f['equity_cash']) + list(S['equity_dist'])
    R['eq_dates'] = dates; R['eq_flows'] = np.array(eq)
    R['equity_irr'] = xirr(eq, dates)
    # project IRR (post-tax): base uses before financing (excl. WC funded) vs CFADS
    pr = [0.0] + list(-(u['base_total'])) + list(S['cfads'] + 0)
    pr[1] -= 0  # LNTP included in month-1 EPC
    R['proj_flows'] = np.array(pr)
    R['project_irr'] = xirr(pr, dates, 0.10)
    pre = [0.0] + list(-(u['base_total'])) + list(S['cfads'] + S['tax'])
    R['project_irr_pretax'] = xirr(pre, dates, 0.10)
    R['equity_npv16_at_fc'] = xnpv(0.16, eq, dates, date(2018, 7, 17))
    cum = np.cumsum(eq)
    pb = [i for i in range(len(cum)) if cum[i] >= 0 and i > 0]
    R['payback_date'] = dates[pb[0]].isoformat() if pb else None

# ----------------------------------------------------------------------------------------
# Sculpting and contract generation
# ----------------------------------------------------------------------------------------
def sculpt_rates(R, w, D, prof):
    """Per-period all-in rate on the scheduled balance for sculpting: weights w by tranche
    (ECA, A, B, COM, SB), swap notional relative to the scheduled balance."""
    mac_ = R['mac']; S = R['S']; p = R['p']; N_s = R['N_s']
    r = np.zeros(NS)
    for t in range(NS):
        base = mac_['base_s'][t]; dcf = S_DAYS[t] / 360
        mg = np.array([1.35, 3.65, 3.40, com_margin(S_YEAR[t])])
        rk = (base + mg) / 100 * (0.5 if 'E4' in ERRS else dcf) * GU
        rk[3] += PRI * S_DAYS[t] / 365
        rsb = sb_rate(mac_, t)
        rem = prof[t:].sum()
        bs = D * rem
        sw = (N_s[t] / bs) * (SWAP_FIX / 100 * 0.5 - base / 100 * dcf) * (-1 if 'E10' in ERRS else 1) if bs > 1e-9 else 0.0
        r[t] = (w[:4] * rk).sum() + w[4] * rsb + sw
    return r

def sculpt(R, D, t_first, t_last, w):
    """Constant-DSCR sculpting: DS_t = CFADS_t / DSCR*, DSCR* = PV(CFADS)/D."""
    S = R['S']; prof = R['prof']
    r = sculpt_rates(R, w, D, prof)
    cf = S['cfads'] + (S['tax'] if 'E8' in ERRS else 0)
    pv = 0.0
    for t in range(t_last, t_first - 1, -1):
        pv = (cf[t] + pv) / (1 + r[t])
    dscr = pv / D
    bal = D; newp = np.zeros(NS); ds = np.zeros(NS)
    for t in range(t_first, t_last + 1):
        ds[t] = cf[t] / dscr
        prin = ds[t] - bal * r[t]
        newp[t] = prin / D; bal -= prin
    return newp, dscr, pv, r, ds

def size_fc(p, gearing=0.75, dscr_target=1.35, down_target=1.20, verbose=False, max_it=200, only_gearing=False):
    """FC sizing: iterate (profile, notional, debt) -> model -> CFADS -> re-sculpt to convergence.
    Debt = min(gearing cap x T, PV(CFADS)/DSCR target, downside-constrained amount)."""
    _, t1 = first_ds_period(p); tl = tix('2034H1')
    prof = np.zeros(NS); prof[t1:tl + 1] = 1.0 / (tl - t1 + 1)
    N_m = np.zeros(NM); N_s = np.zeros(NS)
    D_fixed = None; hist = []
    pd = dict(p); pd.update(SCENARIOS[3]); pd['name'] = 'FC downside'; pd['fund_mode'] = 'size'
    for it in range(1, max_it + 1):
        p['fund_mode'] = 'size'
        R = run(p, prof, N_m, N_s, None, D_fixed, gearing)
        D = R['f']['D']; T = R['f']['T']
        newp, dscr, pv, r, ds = sculpt(R, D, t1, tl, SHARE_W())
        cap_ = pv / dscr_target
        if down_target:
            Rd = run(pd, prof, N_m, N_s, None, D, gearing)
            md = min(Rd['S']['dscr'][t] for t in range(t1, tl + 1))
        else:
            md = 9.99
        cap_down = D * md / down_target
        fe = R['fe']; bal_m = sum(R['f']['bal_' + k] for k in TR)
        newNm = np.zeros(NM); newNm[1:fe + 1] = 0.8 * bal_m[:fe]
        newNs = np.zeros(NS)
        for t in range(t1, NS):
            newNs[t] = 0.8 * D * newp[t:].sum()
        cands = {'gearing': gearing * T, 'DSCR': cap_, 'downside': cap_down if down_target else 1e9}
        bind = 'gearing' if only_gearing else min(cands, key=cands.get)
        newD_fixed = None if bind == 'gearing' else cands[bind]
        diff = max(np.abs((newp - prof) * D).max(), np.abs(newNm - N_m).max(), np.abs(newNs - N_s).max(),
                   abs((newD_fixed or 0) - (D_fixed or 0)))
        hist.append(diff)
        prof, N_m, N_s, D_fixed = newp, newNm, newNs, newD_fixed
        if diff < TOL * 0.01 and it > 2:
            break
    R = run(p, prof, N_m, N_s, None, D_fixed, gearing)
    R['sizing_iterations'] = it; R['sizing_hist'] = hist
    newp, dscr, pv, r, ds = sculpt(R, R['f']['D'], t1, tl, SHARE_W())
    R['sculpt_dscr'] = dscr; R['sculpt_pv'] = pv; R['capacity'] = pv / dscr_target
    R['cands'] = cands; R['downside_min'] = md
    R['sculpt_check'] = np.abs((newp - prof) * R['f']['D']).max()
    R['binding'] = bind
    return R

def SHARE_W():
    return np.array([0.30, 0.22, 0.10, 0.38, 0.0])

def resculpt_cod(p):
    """Lenders' COD re-sculpting on the COD re-forecast case (scenario 14)."""
    _, t1 = first_ds_period(p); tl = tix('2034H1')
    prof = np.zeros(NS); prof[t1:tl + 1] = 1.0 / (tl - t1 + 1)
    for it in range(1, 200):
        R = run(p, prof)
        fe = R['fe']; f = R['f']
        bal = np.array([f['bal_' + k][fe] for k in TR] + [f['bal_SB'][fe]])
        D = bal.sum(); w = bal / D
        newp, dscr, pv, r, ds = sculpt(R, D, t1, tl, w)
        diff = np.abs((newp - prof) * D).max()
        prof = newp
        if diff < TOL * 0.01: break
    R = run(p, prof)
    R['sizing_iterations'] = it
    newp, dscr, pv, r, ds = sculpt(R, D, t1, tl, w)
    R['sculpt_dscr'] = dscr; R['sculpt_check'] = np.abs((newp - prof) * D).max(); R['sculpt_w'] = w
    return R

def bond_sculpt(R):
    """2025 bond: combined DS (ECA + A-loan + bond) sculpted to constant DSCR >= 1.35 to 2037H1."""
    S = R['S']; F = R['bond_F']; t0 = tix('2025H2'); tl = tix('2037H1')
    rb = 7.875 / 100 * 0.5 + 0.011 * 0.5 * 95.0 / F
    other = np.zeros(NS)
    for k in ['ECA', 'A']:
        other += S['interest_' + k] + S['principal_' + k]
    other += S['swap']
    pvc = sum(S['cfads'][t] / (1 + rb) ** (t - t0 + 1) for t in range(t0, tl + 1))
    pvo = sum(other[t] / (1 + rb) ** (t - t0 + 1) for t in range(t0, tl + 1))
    dscr = pvc / (F + pvo)
    bal = F; bp = np.zeros(NS)
    for t in range(t0, tl + 1):
        bds = S['cfads'][t] / dscr - other[t]
        prin = bds - bal * rb
        bp[t] = prin / F; bal -= prin
    return bp, dscr

def solve_actual(p, verbose=False):
    t0 = tix('2025H2'); tl = tix('2037H1')
    bp = np.zeros(NS); bp[t0:tl + 1] = 1.0 / (tl - t0 + 1)
    for it in range(1, 200):
        R = run(p, bond_prof=bp)
        nbp, dscr = bond_sculpt(R)
        diff = np.abs((nbp - bp) * R['bond_F']).max()
        bp = nbp
        if diff < TOL * 0.01: break
    R = run(p, bond_prof=bp)
    nbp, dscr = bond_sculpt(R)
    R['bond_iterations'] = it; R['bond_dscr'] = dscr
    R['bond_check'] = np.abs((nbp - bp) * R['bond_F']).max()
    return R, bp

def build_contract():
    """Run the three sizing problems in story order and fix the contract terms."""
    R1 = size_fc(scen(1))
    f = R1['f']
    CONTRACT.update(Dk=list(f['Dk']), D=f['D'], T=f['T'], E=f['T'] - f['D'],
                    prof_FC=list(R1['prof']), N_m=list(R1['N_m']), N_s=list(R1['N_s']))
    R14 = resculpt_cod(scen(14))
    CONTRACT['prof_COD'] = list(R14['prof'])
    CONTRACT['prof_BOND'] = [0.0] * NS
    R15, bp = solve_actual(scen(15))
    CONTRACT['prof_BOND'] = list(bp)
    return R1, R14, R15


# ========================================================================================
# ANALYSES: figure computations (every ledger figure comes from here)
# ========================================================================================
from contextlib import contextmanager

@contextmanager
def contract_swap(newc):
    old = dict(CONTRACT); CONTRACT.update(newc)
    try:
        yield
    finally:
        CONTRACT.clear(); CONTRACT.update(old)

def oy_months(R, k):
    S = R['S']
    return np.maximum(0, np.minimum(S['ome'], 12 * k) - np.maximum(S['oms'], 12 * (k - 1)))

def oy_sum(R, series, k):
    S = R['S']; w = np.divide(oy_months(R, k), S['om'], out=np.zeros(NS), where=S['om'] > 0)
    return float((np.asarray(series) * w).sum())

def cy_sum(series, y):
    return float(sum(series[t] for t in range(NS) if S_YEAR[t] == y))

def tidx_end(d):
    return [t for t in range(NS) if S_END[t] == d][0]

def ECA_tests(R, cod):
    S = R['S']; P = S['principal_total']; tot = P.sum()
    yrs = np.array([(S_END[t] - cod).days / 365.25 for t in range(NS)])
    wal = float((P * yrs).sum() / tot)
    first = min(t for t in range(NS) if P[t] > 1e-9); last = max(t for t in range(NS) if P[t] > 1e-9)
    m_first = months_between(cod, add_months(date(S_END[first].year, S_END[first].month, 1), 1))
    return dict(wal_years=wal, largest_installment_share=float(P.max() / tot),
                largest_6m_share=float(P.max() / tot), tenor_years=float(yrs[last]),
                first_repayment_months_after_cod=m_first, first_repayment=S_END[first].isoformat(),
                final_maturity=S_END[last].isoformat(),
                pass_tenor_14y=bool(yrs[last] <= 14), pass_wal_7_25=bool(wal <= 7.25),
                pass_25pct=bool(P.max() / tot <= 0.25), pass_first_24m=bool(m_first <= 24),
                pass_first_6m_bible_text=bool(m_first <= 6))

def avg_life_from_fc(R):
    """Balance-weighted average life of the senior loans measured from financial close."""
    f = R['f']; S = R['S']; fe = R['fe']
    bal_m = sum(f['bal_' + k] for k in TR)
    area = sum(bal_m[m - 1] * M_DAYS[m] / 365 for m in range(1, fe + 1))
    area += sum(S['debt_open'][t] * S_DAYS[t] / 365 for t in range(NS) if t > R['t_cod'])
    # draws during the COD period after the last month are captured in bal_m
    return area / R['f']['D']

def dscr_stats(R):
    S = R['S']; m = S['ds'] > 1e-9
    return dict(min_dscr=float(S['dscr'][m].min()), avg_dscr=float(S['cfads'][m].sum() / S['ds'][m].sum()),
                min_hist_dscr=float(S['dscr_hist'][m].min()), llcr_first=float(S['llcr_dsra'][R['t1']]),
                llcr_first_ex_dsra=float(S['llcr'][R['t1']]), plcr_first=float(S['plcr'][R['t1']]),
                lockups=int(S['lockup'].sum()), eod_periods=int(S['eod'].sum()),
                dsra_draws=float(S['dsra_draw'].sum()), unpaid=float(S['shortfall'].sum()))

def summary(R):
    f = R['f']; S = R['S']
    out = dict(T=float(f['T']), D=float(f['D']), E=float(f['equity'].sum()),
               debt_drawn_incl_standby=float(f['debt_draw'].sum()),
               gearing=float(f['debt_draw'].sum() / f['T']),
               equity_irr=float(R['equity_irr']), project_irr=float(R['project_irr']),
               project_irr_pretax=float(R['project_irr_pretax']), npv16_at_fc=float(R['equity_npv16_at_fc']),
               payback_date=R['payback_date'])
    out.update(dscr_stats(R))
    return out

def funding_equity_first(p):
    """Annex variant (P-F43): equity first, then senior debt, at 75% gearing (Python only)."""
    mac_ = build_macro(p); u = construction_uses(p, mac_)
    prof = np.array(CONTRACT['prof_FC']); N_m = np.array(CONTRACT['N_m']); N_s = np.array(CONTRACT['N_s'])
    fe = fund_end_month(p); nc = u['nc']; d1, d0 = dsra_coeffs(p, mac_, prof, N_s)
    T = CONTRACT['T']; log = []
    for it in range(1, 200):
        D = G * T; E = T - D; Dk = SHARE * D
        bal = np.zeros(4); eq = 0.0; uses_tot = 0.0; idc_tot = 0.0; cf_tot = 0.0; prem_tot = 0.0
        for m in range(fe + 1):
            idc_k = bal * (mac_['base_m'][m] + MARGIN) / 100 * M_DAYS[m] / 360 * GU
            pri = PRI * bal[3] * M_DAYS[m] / 365
            # swap accretes with drawn debt: 80% of opening balance
            swap = 0.8 * bal.sum() * (SWAP_FIX / 100 / 12 - mac_['base_m'][m] / 100 * M_DAYS[m] / 360)
            cfee = ((Dk - bal) * CFEE / 100 * M_DAYS[m] / 360).sum()
            sbf = SB_COMMIT * SB_CFEE / 100 * M_DAYS[m] / 360
            upf = (Dk * UPF / 100).sum() if m == 0 else 0.0
            dsra = (d1 * Dk).sum() + d0 if m == nc else 0.0
            X = u['base_total'][m] + u['vat_int'][m] + idc_k.sum() + pri + swap + cfee + sbf + upf + 0.255 / 12 + dsra
            e_m = min(X, E - eq)
            draw = (X - e_m) / (1 - ECA_PREM * SHARE[0])
            prem = ECA_PREM * SHARE[0] * draw
            eq += e_m; bal = bal + SHARE * draw
            uses_tot += X + prem; idc_tot += idc_k.sum() + pri + swap; cf_tot += cfee + sbf; prem_tot += prem
        log.append(uses_tot - T)
        if abs(uses_tot - T) < 1e-9: break
        T = uses_tot
    return dict(T=T, D=G * T, E=(1 - G) * T, idc=idc_tot, commitment_fees=cf_tot, eca_premium=prem_tot,
                iterations=it, note='Equity drawn first, then debt; gearing 75% of the resulting total funding requirement; '
                'swap notional assumed to accrete at 80% of drawn debt; DSCR test not applied (illustrative variant).')

def breakeven(fn, lo, hi, target=1.0, it=60):
    flo = fn(lo) - target
    for _ in range(it):
        mid = (lo + hi) / 2; fm = fn(mid) - target
        if (fm > 0) == (flo > 0): lo, flo = mid, fm
        else: hi = mid
    return (lo + hi) / 2

def min_dscr_of(p):
    R = run(p); S = R['S']; m = S['ds'] > 1e-9
    return float(S['dscr'][m].min())

def monte_carlo(n=1000, seed=20180717):
    rng = np.random.default_rng(seed)
    res = []
    for i in range(n):
        shock = np.clip(rng.normal(0, 2.0, 26), -10, 5)
        disp = rng.triangular(55.0, 76.5, 85.0)
        hrnr = max(0.0, rng.normal(0.12, 0.04))
        fxd = 1 + rng.normal(FX_D - 1, 0.03)
        p = scen(1, avail_shock=shock, dispatch=disp, hr_nr=hrnr, fx_d=fxd)
        R = run(p); S = R['S']; m = S['ds'] > 1e-9
        res.append((S['dscr'][m].min(), S['dscr_hist'][m].min(), R['equity_irr'],
                    int((S['dscr_hist'][m] < 1.20).any()), int((S['dscr_hist'][m] < 1.10).any())))
    a = np.array(res)
    pct = lambda x, q: float(np.percentile(x, q))
    hist_edges = [1.0, 1.1, 1.2, 1.25, 1.3, 1.35, 1.4, 1.5, 9.9]
    counts = np.histogram(a[:, 0], bins=hist_edges)[0]
    return dict(runs=n, seed=seed,
                inputs=dict(availability_shock='per operating year, normal(0, 2.0 points), truncated to -10/+5 points, independent across years',
                            dispatch='one draw per run, triangular(55.0%, 76.5%, 85.0%)',
                            heat_rate_degradation='non-recoverable rate per year, normal(0.12%, 0.04%), floored at 0',
                            fx='KCR depreciation drift per year, normal(5.19%, 3.0%) applied to the FC FX path',
                            debt='locked at the FC base contract (amount and repayment profile)'),
                min_dscr_p10=pct(a[:, 0], 10), min_dscr_p50=pct(a[:, 0], 50), min_dscr_p90=pct(a[:, 0], 90),
                min_hist_dscr_p10=pct(a[:, 1], 10), min_hist_dscr_p50=pct(a[:, 1], 50),
                equity_irr_p10=pct(a[:, 2], 10), equity_irr_p50=pct(a[:, 2], 50), equity_irr_p90=pct(a[:, 2], 90),
                prob_hist_below_1_20=float(a[:, 3].mean()), prob_hist_below_1_10=float(a[:, 4].mean()),
                min_dscr_histogram=dict(edges=hist_edges, counts=[int(c) for c in counts]))

ERR_LIST = ['E%d' % i for i in range(1, 11)]
ERR_DESC = {
    'E1': 'Capacity payment without the availability cap (A/90% not capped at 1)',
    'E2': 'LTSA variable fee on one gas turbine instead of two',
    'E3': 'Tariff indexation reads the index at period end instead of the lagged (Sep/Mar) reading',
    'E4': 'Senior loan interest on 30/360 instead of ACT/360',
    'E5': 'Full tax exemption applied to OY1-OY8 (15% band ignored)',
    'E6': 'Deferred holiday depreciation lost (pool never credited)',
    'E7': 'DSRA initial funding drawn 100% from senior debt instead of pro rata',
    'E8': 'Sculpting on CFADS before tax',
    'E9': 'Fuel-charge revenue uses a typed 76.5% dispatch instead of the live dispatch',
    'E10': 'Swap net settlement with legs reversed',
}

def audit_case(errs):
    p = scen(1, errs=set(errs))
    R = size_fc(p)
    c = dict(D=R['f']['D'], T=R['f']['T'], E=R['f']['T'] - R['f']['D'], Dk=list(R['f']['Dk']),
             prof_FC=list(R['prof']), N_m=list(R['N_m']), N_s=list(R['N_s']))
    with contract_swap(c):
        Rb = run(scen(1, errs=set(errs)))
        Rd = run(scen(3, errs=set(errs)))
    st = dscr_stats(Rb); sd = dscr_stats(Rd)
    return R, c, dict(senior_debt=float(Rb['f']['D']), binding=R['binding'], total_funding=float(Rb['f']['T']),
                      min_dscr_base=st['min_dscr'], avg_dscr_base=st['avg_dscr'], min_dscr_downside=sd['min_dscr'],
                      llcr_at_close=st['llcr_first'], equity_irr=float(Rb['equity_irr']),
                      gearing=float(Rb['f']['debt_draw'].sum() / Rb['f']['T']))

def interp_bs(R, key, d):
    S = R['S']; t1_ = [t for t in range(NS) if S_START[t] <= d <= S_END[t]][0]
    a = S[key][t1_ - 1]; b = S[key][t1_]
    w = (d - S_END[t1_ - 1]).days / S_DAYS[t1_]
    return a + (b - a) * w

def statements(R, t_list):
    """Income statement, cash flow and balance sheet aggregates over periods t_list (end = last)."""
    S = R['S']; t_end = t_list[-1]
    sm = lambda k: float(sum(S[k][t] for t in t_list))
    IS = dict(revenue=sm('revenue'), late_payment_interest=sm('lpi_received'),
              operating_costs=sm('opex'), of_which_fuel_and_transport=sm('pass_cost'), ebitda=sm('ebitda'),
              depreciation=sm('book_dep'), finance_costs=sm('int_exp'),
              of_which_shareholder_loan_interest=sm('shl_int'), current_tax=sm('tax'), deferred_tax=sm('dt_exp'),
              net_income=sm('ni'))
    CF = dict(ebitda=sm('ebitda'), tax_paid=sm('tax'), increase_in_working_capital=sm('dnwc'),
              mmra_net=float(sum(S['mm_contr'][t] - S['mm_spend'][t] for t in t_list)),
              cfads=sm('cfads'), senior_interest_and_fees=sm('senior_costs'), senior_principal=sm('principal_total'),
              ld_prepayment=float(sum(S['ld_prepay_' + k][t] for k in TR + ['SB'] for t in t_list)),
              sweeps=float(sum(S['sweep_' + k][t] for k in TR + ['SB'] for t in t_list)),
              dsra_topup_less_release=float(sum(S['dsra_topup'][t] - S['dsra_release'][t] - S['dsra_draw'][t] for t in t_list)),
              shl_interest_paid=sm('shl_int_paid'), shl_principal_repaid=sm('shl_prin'), dividends=sm('div'))
    BS = dict(date=S_END[t_end].isoformat(), plant=float(S['ppe'][t_end]), cash_in_project_accounts=float(S['bs_cash'][t_end]),
              of_which_dsra=float(S['dsra_close'][t_end]), receivables=float(S['bs_ar'][t_end]),
              of_which_overdue=float(S['overdue'][t_end]), inventory=float(S['bs_inv'][t_end]),
              deferred_tax_asset=float(S['bs_dta'][t_end]), total_assets=float(S['bs_assets'][t_end]),
              senior_debt=float(S['bs_debt'][t_end]), shareholder_loans=float(S['bs_shl'][t_end]),
              payables=float(S['bs_pay'][t_end]), deferred_tax_liability=float(S['bs_dtl'][t_end]),
              share_capital=float(S['bs_sc'][t_end]), retained_earnings=float(S['bs_re'][t_end]),
              total_liabilities_and_equity=float(S['bs_liab_eq'][t_end]), balance_check=float(S['bs_check'][t_end]))
    return dict(income_statement=IS, cash_flow=CF, balance_sheet=BS)

def compute_all():
    F = {}
    R1, R14, R15 = build_contract()
    RS = {i: run(scen(i)) for i in range(1, 16)}
    # sizing details
    Rs = R1; f1 = RS[1]['f']
    gear_T = f1['T_closed_form']
    F['sizing'] = dict(senior_debt=float(f1['D']), total_funding=float(f1['T']), binding=Rs['binding'],
                       candidates={k: float(v) for k, v in Rs['cands'].items()},
                       gearing_cap_debt_closed_form=float(0.75 * gear_T), total_funding_at_75pct_closed_form=float(gear_T),
                       dscr_capacity_at_1_35=float(Rs['capacity']), sculpted_dscr=float(Rs['sculpt_dscr']),
                       downside_min_dscr=float(Rs['downside_min']), sizing_iterations=Rs['sizing_iterations'],
                       sizing_residuals=[float(x) for x in Rs['sizing_hist']],
                       construction_fixed_point_iterations=int(Rs['f']['iterations']),
                       llcr_at_close_incl_dsra=float(RS[1]['S']['llcr_dsra'][RS[1]['t1']]),
                       llcr_at_close_ex_dsra=float(RS[1]['S']['llcr'][RS[1]['t1']]),
                       gearing=float(f1['D'] / f1['T']), tolerance_usd_m=TOL)
    F['summary'] = {i: summary(RS[i]) for i in RS}
    F['scenario_names'] = {i: SCENARIOS[i]['name'] for i in SCENARIOS}
    return F, RS, R1, R14, R15
